---

- name: Ensure file exists
  file:
    path: "{{ environment_file }}"
    owner: "{{ environment_file_owner }}"
    group: "{{ environment_file_group }}"
    state: touch
  register: environment_file_result
  changed_when: environment_file_result.diff.before.state != "file"

- name: Remove previous values
  lineinfile:
    dest: "{{ environment_file }}"
    regexp: '^{{ item.key }}'
    state: absent
  with_dict: "{{ environment_config }}"

- name: Configuring environment
  lineinfile:
    dest: "{{ environment_file }}"
    line: "{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ environment_config }}"
