---

- import_tasks: validate.yml
  tags:
    - validate
    - system
    - environment
    - config
    - environment-config

- import_tasks: config.yml
  tags:
    - system
    - environment
    - config
    - environment-config
